
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 25 13:12:46 CST 2022
//----------------------------------------------------

package ejerciciojflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Asig = 7;
  public static final int Entero = 14;
  public static final int Coma = 43;
  public static final int Nulo = 3;
  public static final int main = 40;
  public static final int If = 20;
  public static final int Id = 16;
  public static final int ExprLogica = 5;
  public static final int LlaveC = 38;
  public static final int LlaveA = 39;
  public static final int Default = 29;
  public static final int Operador = 15;
  public static final int Separador = 8;
  public static final int Else = 21;
  public static final int Read = 45;
  public static final int Break = 27;
  public static final int ExprFinal = 9;
  public static final int Return = 26;
  public static final int While = 23;
  public static final int Division = 35;
  public static final int Int = 18;
  public static final int Flotante = 4;
  public static final int Float = 47;
  public static final int Cadena = 12;
  public static final int For = 24;
  public static final int EOF = 0;
  public static final int DosPuntos = 44;
  public static final int CorcheteC = 42;
  public static final int error = 1;
  public static final int CorcheteA = 41;
  public static final int Switch = 25;
  public static final int Tipo = 2;
  public static final int Char = 17;
  public static final int EstruControl = 13;
  public static final int Print = 30;
  public static final int ERROR = 46;
  public static final int Case = 28;
  public static final int DecInc = 22;
  public static final int Comparador = 11;
  public static final int Parametros = 34;
  public static final int String = 19;
  public static final int Resta = 33;
  public static final int ParentesisC = 36;
  public static final int Boolean = 6;
  public static final int Multiplicacion = 31;
  public static final int ParentesisA = 37;
  public static final int Suma = 32;
  public static final int Comillas = 10;
}

